/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AcceptRequestParams,
  CreateLinkParams,
  CreateRequest200,
  CreateRequestBody,
  Domain,
  GetDomains200Item,
  GetIndexPreview200,
  GetIndexPreviewParams,
  GetLinkByDomainAndPathname200,
  GetLinkByDomainAndPathnameParams,
  GetOgs200Item,
  GetOgsByTag200Item,
  GetOgsParams,
  GetRecentOgs200Item,
  GetRecentSites200Item,
  GetRequestByLink200,
  GetRequestByLinkParams,
  GetRequests200Item,
  GetSites200Item,
  GetSitesByTag200Item,
  GetSitesParams,
  GetV1DomainsDomainDomain200,
  Increase,
  IncreaseClicksParams,
  PostV1EmailCheck200,
  PostV1EmailCheckParams,
  RejectRequestParams,
  Request,
  Sites,
  SubscribeEmail200,
  SubscribeEmailParams,
  UnSubscribeEmail200,
  UnSubscribeEmailParams
} from '../types';




  /**
 * Email
 */
export const postV1EmailCheck = <TData = AxiosResponse<PostV1EmailCheck200>>(
    params?: PostV1EmailCheckParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/email/check`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const subscribeEmail = <TData = AxiosResponse<SubscribeEmail200>>(
    params: SubscribeEmailParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/email/subscribe`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const unSubscribeEmail = <TData = AxiosResponse<UnSubscribeEmail200>>(
    params: UnSubscribeEmailParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/email/unsubscribe`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Get preview of a link
 */
export const getIndexPreview = <TData = AxiosResponse<GetIndexPreview200>>(
    params: GetIndexPreviewParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/indexing/preview`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const createLink = <TData = AxiosResponse<Sites>>(
    params?: CreateLinkParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/links`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const increaseClicks = <TData = AxiosResponse<Increase>>(
    params?: IncreaseClicksParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/links/count/increase`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getLinkByDomainAndPathname = <TData = AxiosResponse<GetLinkByDomainAndPathname200>>(
    domain: Domain & string,
    params?: GetLinkByDomainAndPathnameParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/links/all/${domain}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getRecentSites = <TData = AxiosResponse<GetRecentSites200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/links/sites/recent`,options
    );
  }

export const getSitesByTag = <TData = AxiosResponse<GetSitesByTag200Item[]>>(
    tag: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/links/sites/tag/${tag}`,options
    );
  }

export const getSites = <TData = AxiosResponse<GetSites200Item[]>>(
    params?: GetSitesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/links/sites`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getRecentOgs = <TData = AxiosResponse<GetRecentOgs200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/links/ogs/recent`,options
    );
  }

export const getOgsByTag = <TData = AxiosResponse<GetOgsByTag200Item[]>>(
    tag: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/links/ogs/tag/${tag}`,options
    );
  }

export const getOgs = <TData = AxiosResponse<GetOgs200Item[]>>(
    params?: GetOgsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/links/ogs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getRequests = <TData = AxiosResponse<GetRequests200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/requests`,options
    );
  }

export const createRequest = <TData = AxiosResponse<CreateRequest200>>(
    createRequestBody: CreateRequestBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/requests`,
      createRequestBody,options
    );
  }

export const acceptRequest = <TData = AxiosResponse<Request>>(
    id: string,
    params?: AcceptRequestParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/requests/${id}/accept`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const rejectRequest = <TData = AxiosResponse<Request>>(
    id: string,
    params?: RejectRequestParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/requests/${id}/reject`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getRequestByLink = <TData = AxiosResponse<GetRequestByLink200>>(
    params?: GetRequestByLinkParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://api.yzlab.ru/v1/requests/link`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getDomains = <TData = AxiosResponse<GetDomains200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/domains`,options
    );
  }

export const getV1DomainsDomainDomain = <TData = AxiosResponse<GetV1DomainsDomainDomain200>>(
    domain: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://api.yzlab.ru/v1/domains/domain/${domain}`,options
    );
  }

export type PostV1EmailCheckResult = AxiosResponse<PostV1EmailCheck200>
export type SubscribeEmailResult = AxiosResponse<SubscribeEmail200>
export type UnSubscribeEmailResult = AxiosResponse<UnSubscribeEmail200>
export type GetIndexPreviewResult = AxiosResponse<GetIndexPreview200>
export type CreateLinkResult = AxiosResponse<Sites>
export type IncreaseClicksResult = AxiosResponse<Increase>
export type GetLinkByDomainAndPathnameResult = AxiosResponse<GetLinkByDomainAndPathname200>
export type GetRecentSitesResult = AxiosResponse<GetRecentSites200Item[]>
export type GetSitesByTagResult = AxiosResponse<GetSitesByTag200Item[]>
export type GetSitesResult = AxiosResponse<GetSites200Item[]>
export type GetRecentOgsResult = AxiosResponse<GetRecentOgs200Item[]>
export type GetOgsByTagResult = AxiosResponse<GetOgsByTag200Item[]>
export type GetOgsResult = AxiosResponse<GetOgs200Item[]>
export type GetRequestsResult = AxiosResponse<GetRequests200Item[]>
export type CreateRequestResult = AxiosResponse<CreateRequest200>
export type AcceptRequestResult = AxiosResponse<Request>
export type RejectRequestResult = AxiosResponse<Request>
export type GetRequestByLinkResult = AxiosResponse<GetRequestByLink200>
export type GetDomainsResult = AxiosResponse<GetDomains200Item[]>
export type GetV1DomainsDomainDomainResult = AxiosResponse<GetV1DomainsDomainDomain200>
