/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateLinkParams,
  CreateRequest200,
  CreateRequestBody,
  Domain,
  GetDomains200Item,
  GetIndexPreview200,
  GetIndexPreviewParams,
  GetLinkByDomainAndPathname200,
  GetLinkByDomainAndPathnameParams,
  GetOgs200Item,
  GetOgsByTag200Item,
  GetOgsParams,
  GetRecentOgs200Item,
  GetRecentSites200Item,
  GetRequestByLink200,
  GetRequestByLinkParams,
  GetRequests200Item,
  GetSites200Item,
  GetSitesByTag200Item,
  GetSitesParams,
  GetV1DomainsDomainDomain200,
  Increase,
  IncreaseClicksParams,
  PostV1EmailCheck200,
  PostV1EmailCheckParams,
  Request,
  Sites,
  SubscribeEmail200,
  SubscribeEmailParams,
  UnSubscribeEmail200,
  UnSubscribeEmailParams
} from '../types';

import { axios } from '../lib/custom-instance';
import type { BodyType } from '../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Email
 */
export const postV1EmailCheck = (
    params?: PostV1EmailCheckParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1EmailCheck200>(
      {url: `/v1/email/check`, method: 'POST',
        params
    },
      options);
    }
  
export const subscribeEmail = (
    params: SubscribeEmailParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<SubscribeEmail200>(
      {url: `/v1/email/subscribe`, method: 'POST',
        params
    },
      options);
    }
  
export const unSubscribeEmail = (
    params: UnSubscribeEmailParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<UnSubscribeEmail200>(
      {url: `/v1/email/unsubscribe`, method: 'POST',
        params
    },
      options);
    }
  
/**
 * Get preview of a link
 */
export const getIndexPreview = (
    params: GetIndexPreviewParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetIndexPreview200>(
      {url: `/v1/indexing/preview`, method: 'POST',
        params
    },
      options);
    }
  
export const createLink = (
    params?: CreateLinkParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<Sites>(
      {url: `/v1/links`, method: 'POST',
        params
    },
      options);
    }
  
export const increaseClicks = (
    params?: IncreaseClicksParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<Increase>(
      {url: `/v1/links/count/increase`, method: 'POST',
        params
    },
      options);
    }
  
export const getLinkByDomainAndPathname = (
    domain: Domain & string,
    params?: GetLinkByDomainAndPathnameParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetLinkByDomainAndPathname200>(
      {url: `/v1/links/all/${domain}`, method: 'GET',
        params
    },
      options);
    }
  
export const getRecentSites = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetRecentSites200Item[]>(
      {url: `/v1/links/sites/recent`, method: 'GET'
    },
      options);
    }
  
export const getSitesByTag = (
    tag: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetSitesByTag200Item[]>(
      {url: `/v1/links/sites/tag/${tag}`, method: 'GET'
    },
      options);
    }
  
export const getSites = (
    params?: GetSitesParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetSites200Item[]>(
      {url: `/v1/links/sites`, method: 'GET',
        params
    },
      options);
    }
  
export const getRecentOgs = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetRecentOgs200Item[]>(
      {url: `/v1/links/ogs/recent`, method: 'GET'
    },
      options);
    }
  
export const getOgsByTag = (
    tag: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetOgsByTag200Item[]>(
      {url: `/v1/links/ogs/tag/${tag}`, method: 'GET'
    },
      options);
    }
  
export const getOgs = (
    params?: GetOgsParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetOgs200Item[]>(
      {url: `/v1/links/ogs`, method: 'GET',
        params
    },
      options);
    }
  
export const getRequests = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetRequests200Item[]>(
      {url: `/v1/requests`, method: 'GET'
    },
      options);
    }
  
export const createRequest = (
    createRequestBody: BodyType<CreateRequestBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<CreateRequest200>(
      {url: `/v1/requests`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRequestBody
    },
      options);
    }
  
export const acceptRequest = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<Request>(
      {url: `/v1/requests/${id}/accept`, method: 'POST'
    },
      options);
    }
  
export const rejectRequest = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<Request>(
      {url: `/v1/requests/${id}/reject`, method: 'POST'
    },
      options);
    }
  
export const getRequestByLink = (
    params?: GetRequestByLinkParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetRequestByLink200>(
      {url: `/v1/requests/link`, method: 'POST',
        params
    },
      options);
    }
  
export const getDomains = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetDomains200Item[]>(
      {url: `/v1/domains`, method: 'GET'
    },
      options);
    }
  
export const getV1DomainsDomainDomain = (
    domain: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1DomainsDomainDomain200>(
      {url: `/v1/domains/domain/${domain}`, method: 'GET'
    },
      options);
    }
  
export type PostV1EmailCheckResult = NonNullable<Awaited<ReturnType<typeof postV1EmailCheck>>>
export type SubscribeEmailResult = NonNullable<Awaited<ReturnType<typeof subscribeEmail>>>
export type UnSubscribeEmailResult = NonNullable<Awaited<ReturnType<typeof unSubscribeEmail>>>
export type GetIndexPreviewResult = NonNullable<Awaited<ReturnType<typeof getIndexPreview>>>
export type CreateLinkResult = NonNullable<Awaited<ReturnType<typeof createLink>>>
export type IncreaseClicksResult = NonNullable<Awaited<ReturnType<typeof increaseClicks>>>
export type GetLinkByDomainAndPathnameResult = NonNullable<Awaited<ReturnType<typeof getLinkByDomainAndPathname>>>
export type GetRecentSitesResult = NonNullable<Awaited<ReturnType<typeof getRecentSites>>>
export type GetSitesByTagResult = NonNullable<Awaited<ReturnType<typeof getSitesByTag>>>
export type GetSitesResult = NonNullable<Awaited<ReturnType<typeof getSites>>>
export type GetRecentOgsResult = NonNullable<Awaited<ReturnType<typeof getRecentOgs>>>
export type GetOgsByTagResult = NonNullable<Awaited<ReturnType<typeof getOgsByTag>>>
export type GetOgsResult = NonNullable<Awaited<ReturnType<typeof getOgs>>>
export type GetRequestsResult = NonNullable<Awaited<ReturnType<typeof getRequests>>>
export type CreateRequestResult = NonNullable<Awaited<ReturnType<typeof createRequest>>>
export type AcceptRequestResult = NonNullable<Awaited<ReturnType<typeof acceptRequest>>>
export type RejectRequestResult = NonNullable<Awaited<ReturnType<typeof rejectRequest>>>
export type GetRequestByLinkResult = NonNullable<Awaited<ReturnType<typeof getRequestByLink>>>
export type GetDomainsResult = NonNullable<Awaited<ReturnType<typeof getDomains>>>
export type GetV1DomainsDomainDomainResult = NonNullable<Awaited<ReturnType<typeof getV1DomainsDomainDomain>>>
