/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */
import type { Sites } from './sites';
import type { GetOgsByTag500AllOfItem } from './get-ogs-by-tag500-all-of-item';

export type GetOgsByTag500 = Sites & GetOgsByTag500AllOfItem[];
