/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */

export type GetDomains500Item = {
  id?: string;
  /** @minLength 1 */
  domain: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  favicon?: string | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  last_crawled_at?: string | null;
  created_at?: string;
};
