/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */

export type GetRecentSites500Item = {
  id?: number;
  /** @minLength 1 */
  domain: string;
  /** @minLength 1 */
  pathname: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  favicon?: string | null;
  /** @nullable */
  og?: string | null;
  /** @nullable */
  screenshot?: string | null;
  /** @nullable */
  clicks?: number | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  last_crawled_at?: string | null;
  created_at?: string;
  /** @nullable */
  blurImageURL: string | null;
};
