/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */
import type { GetIndexPreview200Screenshot } from './get-index-preview200-screenshot';

export type GetIndexPreview200 = {
  id?: number;
  /** @minLength 1 */
  domain: string;
  /** @minLength 1 */
  pathname: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  favicon?: string | null;
  /** @nullable */
  og?: string | null;
  /** @nullable */
  screenshot: GetIndexPreview200Screenshot;
  /** @nullable */
  clicks?: number | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  last_crawled_at?: string | null;
  created_at?: string;
};
