/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */

export type GetRequests500Item = {
  id?: number;
  /** @minLength 1 */
  url: string;
  /** @minLength 1 */
  type: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  email?: string | null;
  created_at?: string;
};
