/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */
import type { Sites } from './sites';
import type { GetOgsByTag200AllOfItem } from './get-ogs-by-tag200-all-of-item';

export type GetOgsByTag200 = Sites & GetOgsByTag200AllOfItem[];
