/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZLAB API
 * It's YZLAB API
 * OpenAPI spec version: 1.0.0
 */

export type IncreaseClicksParams = {
id?: string;
path?: string;
domain?: string;
};
